---

- name: Fail When Using Wrong mongodb_version Variable with Debian 8 (Jessie)
  fail:
    msg: "mongodb_version variable should be '3.4' or '3.6' or '4.0' for Debian 8 (Jessie)"
  when:
    - mongodb_package == 'mongodb-org'
    - mongos_package == 'mongodb-org-mongos'
    - mongodb_major_version is not regex("3.4|3.6|4.0")
    - ansible_distribution_release == 'jessie'
  tags: [mongodb, mongos, mongodb-install, mongos-install]

- name: Fail When Using Wrong mongodb_version Variable with Debian 9 (Stretch)
  fail:
    msg: "mongodb_version variable should be '3.6' or '4.0' or '4.2' or '4.4' or '5.0' or '6.0' for Debian 9 (Stretch)"
  when:
    - mongodb_package == 'mongodb-org'
    - mongos_package == 'mongodb-org-mongos'
    - mongodb_major_version is not regex("3.6|4.0|4.2|4.4|5.0|6.0")
    - ansible_distribution_release == 'stretch'
  tags: [mongodb, mongos, mongodb-install, mongos-install]

- name: Fail When Using Wrong mongodb_version Variable with Debian 10 (Buster)
  fail:
    msg: "mongodb_version variable should be '4.2' or '4.4' or '5.0' or '6.0' for Debian 10 (Buster)"
  when:
    - mongodb_package == 'mongodb-org'
    - mongos_package == 'mongodb-org-mongos'
    - mongodb_major_version is not regex("4.2|4.4|5.0|6.0")
    - ansible_distribution_release == 'buster'
  tags: [mongodb, mongos, mongodb-install, mongos-install]

- name: Fail When Using Wrong mongodb_version Variable with Debian 11 (Bullseye)
  fail:
    msg: "mongodb_version variable should be '5.0' or '6.0' for Debian 11 (Bullseye)"
  when:
    - mongodb_package == 'mongodb-org'
    - mongos_package == 'mongodb-org-mongos'
    - mongodb_major_version is not regex("5.0|6.0")
    - ansible_distribution_release == 'bullseye'
  tags: [mongodb, mongos, mongodb-install, mongos-install]

- name: Fail When Using Wrong mongodb_version Variable with Ubuntu 16.04 (Xenial)
  fail:
    msg: "mongodb_version variable should be '3.4' or '3.6' or '4.0' or '4.2' or '4.4' or '5.0' or '6.0' for Ubuntu 16.04 (Xenial)"
  when:
    - mongodb_package == 'mongodb-org'
    - mongos_package == 'mongodb-org-mongos'
    - mongodb_major_version is not regex("3.4|3.6|4.0|4.2|4.4|5.0|6.0")
    - ansible_distribution_release == "xenial"
  tags: [mongodb, mongos, mongodb-install, mongos-install]

- name: Fail When Using Wrong mongodb_version Variable with Ubuntu 18.04 (Bionic)
  fail:
    msg: "mongodb_version variable should be '3.6' or '4.0' or '4.2' or '4.4' or '5.0' or '6.0' for Ubuntu 18.04 (Bionic)"
  when:
    - mongodb_package == 'mongodb-org'
    - mongos_package == 'mongodb-org-mongos'
    - mongodb_major_version is not regex("3.6|4.0|4.2|4.4|5.0|6.0")
    - ansible_distribution_release == "bionic"
  tags: [mongodb, mongos, mongodb-install, mongos-install]

- name: Fail When Using Wrong mongodb_version Variable with Ubuntu 20.04 (Focal)
  fail:
    msg: "mongodb_version variable should be '4.4' or '5.0' or '6.0' for Ubuntu 20.04 (Focal)"
  when:
    - mongodb_package == 'mongodb-org'
    - mongos_package == 'mongodb-org-mongos'
    - mongodb_major_version is not regex("4.4|5.0|6.0")
    - ansible_distribution_release == "focal"
  tags: [mongodb, mongos, mongodb-install, mongos-install]

- name: Fail When Using Wrong mongodb_version Variable with Ubuntu 22.04 (Jammy)
  fail:
    msg: "mongodb_version variable should be '6.0' for Ubuntu 22.04 (Jammy)"
  when:
    - mongodb_package == 'mongodb-org'
    - mongos_package == 'mongodb-org-mongos'
    - mongodb_major_version is not regex("6.0")
    - ansible_distribution_release == "jammy"
  tags: [mongodb, mongos, mongodb-install, mongos-install]

- name: Fail When Using Wrong ansible_distribution_release
  fail:
    msg: "ansible_distribution_release should be 'Debian 8 (Jessie)' or 'Debian 9 (Stretch)' or 'Debian 10 (Buster)' or 'Debian 11 (Bullseye)' or 'Ubuntu 16.04 (Xenial)' or 'Ubuntu 18.04 (Bionic)' or 'Ubuntu 20.04 (Focal)' or 'Ubuntu 22.04 (Jammy)'"
  when:
    - ansible_distribution_release is not regex("xenial|stretch|buster|bullseye|bionic|focal|jammy")
  tags: [mongodb, mongos, mongodb-install, mongos-install]

- name: Disable Transparent Huge Pages on Systemd Systems
  include_tasks: disable_transparent_hugepages.yml
  when:
    - mongodb_disable_transparent_hugepages
    - ansible_service_mgr == "systemd"
  tags: [mongodb, mongos, mongodb-install, mongos-install]

- name: Shell Apt Update to Allow Repository Change
  shell: apt update -y --allow-releaseinfo-change
  changed_when: false
  tags: [mongodb, mongos, mongodb-install, mongos-install]

- name: Install Gnupg Package
  apt:
    name: gnupg
    state: present
    update_cache: true
  tags: [mongodb, mongos, mongodb-install, mongos-install]

- name: Add APT Key for MongoDB Repository
  apt_key:
    url: "{{ mongodb_apt_key_url }}"
    state: present
  register: _apt
  until: _apt is succeeded
  retries: 5
  when: 
    - mongodb_package == 'mongodb-org'
    - mongos_package == 'mongodb-org-mongos'
  tags: [mongodb, mongos, mongodb-install, mongos-install]

- name: Add MongoDB APT Repository
  apt_repository:
    repo: "{{ mongodb_repository[mongodb_major_version] }}"
    filename: "mongodb-{{ mongodb_version }}"
  register: _apt
  until: _apt is succeeded
  retries: 5
  when:
    - mongodb_package == 'mongodb-org'
    - mongos_package == 'mongodb-org-mongos'
  tags: [mongodb, mongos, mongodb-install, mongos-install]

- name: Install MongoDB Package '{{ mongodb_version }}'
  apt:
    name: 
      - "{{ mongodb_package + '-server=' + mongodb_version if mongodb_version | length > 3 else mongodb_package + '-server' }}"
      - "{{ mongodb_package + '-shell=' + mongodb_version if mongodb_version | length > 3 else mongodb_package + '-shell' }}"
      - "{{ mongodb_package + '-tools=' + mongodb_version if mongodb_version | length > 3 else mongodb_package + '-tools' }}"
    state: "{{ mongodb_package_state }}"
    update_cache: true
    force: "{{ mongodb_force_install }}"
  when: mongodb_main_group != mongos_host_group
  tags: [mongodb, mongodb-install]

- name: Install Mongos Package '{{ mongos_version }}'
  apt:
    name: "{{ mongos_package + '=' + mongos_version if mongos_version | length > 3 else mongos_package }}"
    state: "{{ mongos_package_state }}"
    update_cache: true
    force: "{{ mongos_force_install }}"
  when: mongodb_main_group == mongos_host_group
  tags: [mongos, mongos-install]

- name: Install Mongosh When MongoDB Version >= '4.4'
  apt:
    name: mongodb-mongosh
    state: present
  when: mongodb_major_version is version('4.4', '>=')
  tags: [mongodb, mongos, mongodb-install, mongos-install]

- name: Install Numactl Package
  apt:
    name: numactl
    state: present
  when: mongodb_use_numa
  tags: [mongodb, mongos, mongodb-install, mongos-install]
